name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  my-job:
    name: CI/CD Infra
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master branch
        uses: actions/checkout@v2

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1

#      - name: Deploy IaC
#        run: aws cloudformation deploy --template-file src/infra/autoscaling_tropo.yaml --stack-name infra-stack